# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: marvel_api 0.2.0 ruby lib

Gem::Specification.new do |s|
  s.name = "marvel_api"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Rahul Hor\u{e9}"]
  s.date = "2014-05-24"
  s.description = "Marvel_API is a Ruby gem that lets you explore the Marvel Universe like never before."
  s.email = "hore.rahul@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".travis.yml",
    "Gemfile",
    "Guardfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/marvel/client.rb",
    "lib/marvel/configuration.rb",
    "lib/marvel/connection.rb",
    "lib/marvel/request.rb",
    "lib/marvel_api.rb",
    "marvel_api.gemspec",
    "spec/fixtures/characters/character.json",
    "spec/fixtures/characters/character_comics.json",
    "spec/fixtures/characters/character_events.json",
    "spec/fixtures/characters/character_series.json",
    "spec/fixtures/characters/character_stories.json",
    "spec/fixtures/characters/characters.json",
    "spec/fixtures/comics/comic.json",
    "spec/fixtures/comics/comic_characters.json",
    "spec/fixtures/comics/comic_creators.json",
    "spec/fixtures/comics/comic_events.json",
    "spec/fixtures/comics/comic_stories.json",
    "spec/fixtures/comics/comics.json",
    "spec/fixtures/creators/creator.json",
    "spec/fixtures/creators/creator_comics.json",
    "spec/fixtures/creators/creator_events.json",
    "spec/fixtures/creators/creator_series.json",
    "spec/fixtures/creators/creator_stories.json",
    "spec/fixtures/creators/creators.json",
    "spec/fixtures/events/event.json",
    "spec/fixtures/events/event_characters.json",
    "spec/fixtures/events/event_comics.json",
    "spec/fixtures/events/event_creators.json",
    "spec/fixtures/events/event_series.json",
    "spec/fixtures/events/event_stories.json",
    "spec/fixtures/events/events.json",
    "spec/fixtures/series/serie.json",
    "spec/fixtures/series/series.json",
    "spec/fixtures/series/series_characters.json",
    "spec/fixtures/series/series_comics.json",
    "spec/fixtures/series/series_creators.json",
    "spec/fixtures/series/series_events.json",
    "spec/fixtures/series/series_stories.json",
    "spec/fixtures/stories/stories.json",
    "spec/fixtures/stories/story.json",
    "spec/fixtures/stories/story_characters.json",
    "spec/fixtures/stories/story_comics.json",
    "spec/fixtures/stories/story_creators.json",
    "spec/fixtures/stories/story_events.json",
    "spec/fixtures/stories/story_series.json",
    "spec/marvel_api/client/client_character_spec.rb",
    "spec/marvel_api/client/client_comic_spec.rb",
    "spec/marvel_api/client/client_creator_spec.rb",
    "spec/marvel_api/client/client_event_spec.rb",
    "spec/marvel_api/client/client_series_spec.rb",
    "spec/marvel_api/client/client_story_spec.rb",
    "spec/marvel_api_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/O-I/marvel"
  s.licenses = ["MIT"]
  s.required_ruby_version = Gem::Requirement.new(">= 1.9.3")
  s.rubygems_version = "2.2.2"
  s.summary = "Ruby bindings for the Marvel API"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<faraday>, [">= 0"])
      s.add_runtime_dependency(%q<faraday_middleware>, [">= 0"])
      s.add_runtime_dependency(%q<hashie>, [">= 0"])
      s.add_development_dependency(%q<pry>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.7"])
    else
      s.add_dependency(%q<faraday>, [">= 0"])
      s.add_dependency(%q<faraday_middleware>, [">= 0"])
      s.add_dependency(%q<hashie>, [">= 0"])
      s.add_dependency(%q<pry>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.7"])
    end
  else
    s.add_dependency(%q<faraday>, [">= 0"])
    s.add_dependency(%q<faraday_middleware>, [">= 0"])
    s.add_dependency(%q<hashie>, [">= 0"])
    s.add_dependency(%q<pry>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.7"])
  end
end